apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: family-tree
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jiazu.xiarui.net
    secretName: jiazu-secret
  rules:
  - host: jiazu.xiarui.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: family-tree
            port:
              number: 80
